---
title: "Dyad-Individual-Model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Dyad-Individual-Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(interdep)
has_glmmTMB <- requireNamespace("glmmTMB", quietly = TRUE)
```


## Cross-Sectional Gaussian DIM

We prepare the data with the `interdep::prepare_interdep_data()` function:

```{r prepare-cross-distinguishable}
cross_distinguishable_data <- prepare_interdep_data(
  example_dyadic_crosssectional,
  group = coupleID,
  role = gender,
  member = personID,
  predictors = communication,
  model_type = "dim",
  seed = 123
)

print(cross_distinguishable_data, n = 20)

```

### Example DIM Model

```{r}

dim_1 <- glmmTMB(
  satisfaction ~ 1 + 
    .i_communication_raw_dyad_mean + .i_communication_raw_within_dyad_deviation +
    
    (1 | coupleID) + (0 + .i_diff | coupleID)
)

```

